version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped  
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: unless-stopped  
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    volumes:
      - "./kafka_data:/bitnami"
    # environment:
    #   - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #   - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

 #docker compose up   
#https://stackoverflow.com/questions/53089486/unable-to-connect-to-kafka-run-in-container-from-spring-boot-app-run-outside-con
